source :rubygems

ruby '1.9.3'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-authentication'
gem 'rack-ssl'
gem 'foreman'
gem 'datamapper'
gem 'dm-postgres-adapter'
gem 'dm-observer'
gem 'pusher'
gem 'thin'
gem 'rack-flash3'
gem 'phonie', git: 'git://github.com/wmoxam/phonie.git'
gem 'facets'    
gem 'tropo-webapi-ruby'
gem 'tropo-provisioning'
gem 'nexmo'
gem 'plivo'
gem 'rspec'
gem 'fakeweb'
gem 'pusher-fake'
gem 'resque'
gem 'twilio-ruby'
gem 'rake'
gem 'capybara'
gem 'haml'
gem 'lazy_high_charts', git: 'git://github.com/michelson/lazy_high_charts.git'
gem 'statsd-ruby', require: 'statsd'
gem 'racksh'
gem 'sinatra-jsonp'
gem "actionpack", "~> 3.2.11"