source :rubygems

ruby '1.9.3'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-authentication'
gem 'twilio-ruby'
gem 'foreman'
gem 'datamapper'
gem 'dm-postgres-adapter'
gem 'dm-observer'
gem 'pusher'
gem 'thin'
gem 'rack-flash3'
gem 'phone', git: 'git://github.com/wmoxam/phone.git'
gem 'facets'
gem 'tropo-webapi-ruby'
gem 'tropo-provisioning'
gem 'nexmo'
gem 'rspec'
gem 'fakeweb'
gem 'pusher-fake'
gem 'resque'
gem 'rake'
gem 'capybara'
gem 'haml'
gem 'lazy_high_charts'
gem 'statsd-ruby', require: 'statsd'