source :rubygems

ruby '1.9.3'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'twilio-ruby'
gem 'foreman'
gem 'datamapper'
gem 'dm-postgres-adapter'
gem 'pusher'
gem 'thin'
gem 'rack-flash3'
gem 'phone'
gem 'facets'
gem 'tropo-webapi-ruby'
gem 'tropo-provisioning'
gem 'rspec'
gem 'fakeweb'
gem 'pusher-fake'
gem 'resque'
gem 'rake'
gem 'capybara'